### ISSUE TITLE
Attempt to make a symlink on Windows

### ISSUE THREAD

**Issue by iwane-pl** [spirali/nedoc#5]
nedoc attempts to make a symlink on Windows (at the end of `writesrc` step), what results in `OSError: symbolic link privilege not held`.

OS: Win10 Enteprise, build 16299
Regular user (no admin rights)

**Comment by iwane-pl** [comment]
Full traceback:
> Traceback (most recent call last):
  File "C:\Python36_x86\python-3.6.1\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python36_x86\python-3.6.1\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\repos\nedoc\nedoc\__main__.py", line 4, in <module>
    main()
  File "c:\repos\nedoc\nedoc\cmd.py", line 72, in main
    c.build()
  File "c:\repos\nedoc\nedoc\core.py", line 112, in build
    self.render()
  File "c:\repos\nedoc\nedoc\core.py", line 166, in render
    self.make_index()
  File "c:\repos\nedoc\nedoc\core.py", line 133, in make_index
    os.symlink(target, index)
OSError: symbolic link privilege not held

**Comment by spirali** [comment]
Thank you for reporting. Symlink is used only for index.html. I have added a fallback when a file is copied instead of symlinked.

**Comment by iwane-pl** [comment]
Works, thank you!
